# Generated by Django 4.1.3 on 2022-11-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('precio', models.IntegerField()),
                ('fabricante', models.TextField(max_length=200)),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
