# Generated by Django 4.1.3 on 2022-11-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.PositiveIntegerField(),
        ),
    ]
