# Generated by Django 4.1.3 on 2022-11-19 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_rename_name_productos_nombre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos',
            new_name='Producto',
        ),
    ]
