# Generated by Django 4.1.3 on 2022-11-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='Descripcion', max_length=500),
            preserve_default=False,
        ),
    ]
