# Generated by Django 4.1.3 on 2022-11-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='img',
            field=models.ImageField(default='media/1.jpg', upload_to='media'),
            preserve_default=False,
        ),
    ]
