# Generated by Django 4.1.3 on 2022-11-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_carro_itemcarro'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='id_carro',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
