# Generated by Django 4.1.3 on 2022-11-23 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_carro_id_carro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente de envio'), ('ENV', 'Enviado'), ('ENT', 'Pedido entregado')], default='PEN', max_length=3)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.carro')),
            ],
        ),
    ]
