# Generated by Django 4.1.3 on 2022-11-25 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_alter_cliente_codigo_postal'),
        ('homepage', '0013_itempedido'),
    ]

    operations = [
    ]
