# Generated by Django 4.1.3 on 2022-12-02 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_merge_20221125_1151'),
        ('homepage', '0016_auto_20221130_2013'),
    ]

    operations = [
    ]
