# Generated by Django 3.1.7 on 2022-12-05 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_alter_carro_id_alter_cliente_id_alter_itemcarro_id_and_more'),
        ('homepage', '0017_alter_carro_id_alter_cliente_id_alter_itemcarro_id_and_more'),
    ]

    operations = [
    ]
