# Generated by Django 4.1.3 on 2022-12-05 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_alter_producto_nombre'),
        ('homepage', '0019_merge_20221205_1829'),
    ]

    operations = [
    ]
