# Generated by Django 4.1.3 on 2022-12-07 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0020_merge_20221205_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='carro',
        ),
    ]
