# Generated by Django 4.1.3 on 2022-12-07 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0021_remove_pedido_carro'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='carro',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='homepage.carro'),
            preserve_default=False,
        ),
    ]
