# Generated by Django 4.1.3 on 2022-12-07 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0022_pedido_carro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='carro',
        ),
    ]
